### ISSUE TITLE
Considerations

### ISSUE THREAD

**Issue by Master-64** [Kaboms/Shrek-2-Remake#1]
Hello, I'm Master_64.

You likely already know who I am, but if you don't, I'm the player who has over 25k+ hours in the original Shrek 2 (PC) game. I'd like to provide assistance in making this project actually represent the original game. At the moment, this project seems to lack a proper playtester, at least based on the gameplay footage I've observed. A majority of the gameplay I saw doesn't truly represent the essence of what makes Shrek 2 (PC) what it is today. I can take your project to the next level, if you'll let me. Consider getting in contact with me.

**Comment by Kaboms** [comment]
Hello. I really appreciate your interest in this project. In my opinion, the project is far enough away from even alpha status that there aren't many things to test.

**Comment by DRSDavidSoft** [comment]
@Master-64 Since you do know the original Shrek 2 game intimately, I'd appreciate having your insights as well as maybe covering it on YouTube, if you haven't done so already.

On a side note, there have been multiple Unreal 5 attempts of making a Shrek game, and they look amazing, sad to see that they didn't converge into one. Would be amazing to see a full recreation of the original game, and maybe be able to extend it! 👍🏻
